# Generated by Django 3.2.3 on 2021-05-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('league', models.CharField(blank=True, choices=[('National', 'Ntional'), ('American', 'American')], max_length=10)),
                ('division', models.CharField(blank=True, choices=[('East', 'East'), ('Central', 'Central'), ('West', 'West')], max_length=10)),
            ],
        ),
    ]
