# Generated by Django 3.2.3 on 2021-05-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.CharField(blank=True, choices=[('National', 'National'), ('American', 'American')], max_length=10),
        ),
    ]
