# Generated by Django 3.2.3 on 2021-05-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='opp_runs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tor_runs',
            field=models.IntegerField(),
        ),
    ]
