# Generated by Django 3.2.3 on 2021-05-27 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210525_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='tor_runs',
            new_name='team_runs',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='tor_starter',
            new_name='team_starter',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='tor_win_prob',
            new_name='team_win_prob',
        ),
    ]
