# Generated by Django 3.2.3 on 2021-05-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210527_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='w_or_l',
            field=models.CharField(blank=True, choices=[('W', 'W'), ('L', 'L'), ('', 'Null')], max_length=10, null=True),
        ),
    ]
