# Generated by Django 3.2.3 on 2021-05-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_schedule_w_or_l'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='w_or_l',
            field=models.CharField(blank=True, choices=[('W', 'W'), ('L', 'L'), ('None', 'Null')], max_length=10, null=True),
        ),
    ]
